import React from 'react'

const Overview = () => {
  return (
    <div className='max-w-[1100px] w-full mx-auto   py-10 mt-8'>
      <h1 className='capitalize flex justify-center text-[#7367F0] bg-gradient-to-r from-transparent via-[#46555C] to-transparent font-semibold text-[2.5rem]'>
        Student Management System 
      </h1>

      <p className='px-[2rem] py-[2rem] text-center text-[#ccc] mt-4 rounded-md text-[1.2rem]  max-w-[700px] mx-auto'>  
      "Student Management System Nextlevelbot  is a solution tool that is designed to track, maintain and manage all the data generated by a School, including the grades of a student, their attendance, their interpersonal activities records, etc.,"

</p>


    </div>
  )
}

export default Overview